### ISSUE TITLE
Hit error when trying to run the sample code, please help!

### ISSUE THREAD

**Issue by jasonlaw** [Andrious/weathercast#1]
Launching lib\main.dart on SM G950F in debug mode...
* Error running Gradle:
ProcessException: Process "C:\JSL\Codelab\flutter\mvc\weathercast-master\android\gradlew.bat" exited abnormally:
FAILURE: Build failed with an exception.
* Where:
Build file 'C:\JSL\Codelab\flutter\mvc\weathercast-master\android\app\build.gradle' line: 45
* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1s
Picked up _JAVA_OPTIONS: -Xmx512M
  Command: C:\JSL\Codelab\flutter\mvc\weathercast-master\android\gradlew.bat app:properties
Please review your Gradle project setup in the android/ folder.
Exited (sigterm)

**Comment by Andrious** [comment]
Hi, Jason.  Let me take a look for you... one moment.

**Comment by Andrious** [comment]
You'll only be able to under that app in your chosen IDE.

Have you got in working in your IDE?

**Comment by jasonlaw** [comment]
I am using VSCode, and that's the error when I try to run the app (Start Debuging).

**Comment by jasonlaw** [comment]
Could it be something to do with the keystore?

**Comment by Andrious** [comment]
Indeed it does. You don't have one. 

I'll try something on my end, but in the meantime, would you try commenting out the following from your 'app' gradle file:

  signingConfigs {
        release{
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
            v2SigningEnabled false
        }
    }

**Comment by jasonlaw** [comment]
After comment out the signingconfig and release config, it works now. Thanks for the great article and framework!

**Comment by Andrious** [comment]
Good.

And thanks.
